# Generated by Django 4.1.3 on 2022-11-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='This is the slug form of the title of your blog post', max_length=150, unique_for_date='publish'),
        ),
    ]
